# Generated by Django 5.2 on 2025-04-27 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messengeruser',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-last_updated'], 'verbose_name': 'Conversation', 'verbose_name_plural': 'Conversations'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='page_access_token',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='page_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='system_prompt',
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='messages',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='sender_id',
            field=models.CharField(max_length=255, verbose_name='Sender ID (PSID)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='meta_access_token',
            field=models.CharField(blank=True, help_text='Stores the user-level Meta access token (long-lived if possible).', max_length=512, null=True),
        ),
        migrations.CreateModel(
            name='ConnectedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(help_text='The unique Facebook or Instagram Page ID.', max_length=255, unique=True, verbose_name='Page ID')),
                ('page_name', models.CharField(blank=True, help_text='The name of the Facebook or Instagram Page.', max_length=255, null=True, verbose_name='Page Name')),
                ('page_access_token', models.CharField(help_text='The access token specific to this page.', max_length=512, verbose_name='Page Access Token')),
                ('system_prompt', models.TextField(blank=True, help_text='AI instructions for interacting via this page. Leave blank to use a default.', null=True, verbose_name='Page-Specific AI System Prompt')),
                ('connected_at', models.DateTimeField(auto_now_add=True, verbose_name='Connected At')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('is_active', models.BooleanField(default=True, help_text='Webhook events will only be processed for active pages.', verbose_name='Is Active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Connected Page',
                'verbose_name_plural': 'Connected Pages',
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='connected_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='socialapp.connectedpage'),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('connected_page', 'sender_id')},
        ),
        migrations.DeleteModel(
            name='CombinedMessage',
        ),
        migrations.DeleteModel(
            name='MessengerUser',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='user',
        ),
    ]
