# Generated by Django 4.2.3 on 2025-03-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0002_messengeruser_combinedmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='page_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='page_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='meta_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
