# Generated by Django 4.2.3 on 2025-04-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0003_customuser_is_paid_customuser_page_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('messages', models.JSONField()),
                ('sender_id', models.CharField(max_length=20)),
            ],
        ),
    ]
