"""
Django settings for social_manager project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


META_APP_ID = '1152489759401130'
META_APP_SECRET = '6637d283f19db96a3b243134fa70249c'
#META_REDIRECT_URI = 'http://localhost:8000/auth/meta/callback/'

# META_REDIRECT_URI = 'https://socialmanager.ge/auth/meta/callback/'
# LOGIN_REDIRECT_URL = 'https://socialmanager.ge/home/'


META_REDIRECT_URI = 'http://localhost:8000/auth/meta/callback/'
LOGIN_REDIRECT_URL = 'http://localhost:8000/home/'
AUTH_USER_MODEL = 'socialapp.CustomUser'
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(5hlz5l%(kuc!4g!)!1b5)wozz8o*2(i6tb571+%th1q^xap4o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
     'django.contrib.humanize',
    'socialapp',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    
    
]

ROOT_URLCONF = 'social_manager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'social_manager.wsgi.application'


LANGUAGES = [
    ('en', _('English')),
    ('ka', _('Georgian')),
 
    # Add more as needed
]
LOCALE_PATHS = [
    Path().joinpath(BASE_DIR) / 'locale',
]
# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True
USE_L10N = True 

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL =  'static/'


STATIC_ROOT ="/home/socialma/public_html/static/"


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SITE_ID = 1  # Required for django.contrib.sites

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

 # Where users go after login
LOGOUT_REDIRECT_URL = '/'  # Where users go after logout

# Optional: Disable email verification if you only want Facebook login
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'email'
  # Or 'username' if preferred

SOCIALACCOUNT_LOGIN_ON_GET = True

SOCIALACCOUNT_PROVIDERS = {
    'facebook': {
        # --- Settings for Facebook Login via Allauth ---
        'METHOD': 'oauth2', # Default, specifies the login method
        'SCOPE': ['email', 'public_profile'], # Basic permissions needed for login
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'}, # Optional: forces re-auth
        'INIT_PARAMS': {'cookie': True}, # Optional: FB JavaScript SDK init
        'FIELDS': [ # Data to fetch from Facebook after login
            'id',
            'email',
            'name',
            'first_name',
            'last_name',
            # 'verified', # Needs app review potentially
            'locale',
            'timezone',
            'link',
            'gender',
            'updated_time',
        ],
        'EXCHANGE_TOKEN': True, # Exchange code for token
        'LOCALE_FUNC': lambda request: 'en_US', # Or dynamically get locale
        'VERIFIED_EMAIL': False, # Set to True if you trust FB verified email status
        'VERSION': 'v22.0', # Use a specific, current API version
        'APP': { # Your App Credentials for LOGIN
            'client_id': '1152489759401130', # Should match the FB App
            'secret': '6637d283f19db96a3b243134fa70249c', # Should match the FB App
            'key': '' # Usually leave blank
        }
    }
}
